# Generated by Django 4.0 on 2022-03-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_category_pptmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='pptmodel',
        ),
    ]
