# Generated by Django 4.0.3 on 2022-03-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_exam_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_model',
            old_name='outputs',
            new_name='inputs',
        ),
        migrations.RenameField(
            model_name='exam_model',
            old_name='u',
            new_name='select_user',
        ),
    ]
